// examples/react/src/pages/use-chain-wallet.tsx
import { useChainWallet } from "@interchain-kit/react";

const UseChainWallet = () => {
  const junoInKeplrWallet = useChainWallet("juno", "keplr-extension");
  const stargazeInKeplrWallet = useChainWallet("stargaze", "keplr-extension");
  const junoInLeap = useChainWallet("juno", "leap-extension");
  const stargazeInLeap = useChainWallet("stargaze", "leap-extension");
  return (
    <div>
      <table>
        <tbody>
          <tr>
            <td>keplr - juno</td>
            <td>{junoInKeplrWallet.address}</td>
            <td>
              <button
                className="bg-green-300 px-1"
                onClick={junoInKeplrWallet.connect}
              >
                connect
              </button>
            </td>
            <td>
              <button
                className="bg-red-300 px-1"
                onClick={junoInKeplrWallet.disconnect}
              >
                disconnect
              </button>
            </td>
          </tr>
          <tr>
            <td>keplr - stargaze</td>
            <td>{stargazeInKeplrWallet.address}</td>
            <td>
              <button
                className="bg-green-300 px-1"
                onClick={stargazeInKeplrWallet.connect}
              >
                connect
              </button>
            </td>
            <td>
              <button
                className="bg-red-300 px-1"
                onClick={stargazeInKeplrWallet.disconnect}
              >
                disconnect
              </button>
            </td>
          </tr>
          <tr>
            <td>leap - juno</td>
            <td>{junoInLeap.address}</td>
            <td>
              <button
                className="bg-green-300 px-1"
                onClick={junoInLeap.connect}
              >
                connect
              </button>
            </td>
            <td>
              <button
                className="bg-red-300 px-1"
                onClick={junoInLeap.disconnect}
              >
                disconnect
              </button>
            </td>
          </tr>
          <tr>
            <td>leap - stargaze</td>
            <td>{stargazeInLeap.address}</td>
            <td>
              <button
                className="bg-green-300 px-1"
                onClick={stargazeInLeap.connect}
              >
                connect
              </button>
            </td>
            <td>
              <button
                className="bg-red-300 px-1"
                onClick={stargazeInLeap.disconnect}
              >
                disconnect
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};
export default UseChainWallet;

// examples/vue/src/views/use-chain-wallet.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useChainWallet, useWalletManager } from '@interchain-kit/vue';
const junoChainName = ref('juno')
const stargazeChainName = ref('stargaze')
const keplrWalletName = ref('keplr-extension')
const leapWalletName = ref('leap-extension')

const junoInKeplrWallet = useChainWallet(junoChainName, keplrWalletName);
const stargazeInKeplrWallet = useChainWallet(stargazeChainName, keplrWalletName);
const junoInLeapWallet = useChainWallet(junoChainName, leapWalletName);
console.log('junoInLeapWallet', junoInLeapWallet)
const stargazeInLeapWallet = useChainWallet(stargazeChainName, leapWalletName);
</script>

<template>
	<div>
		<table>
			<tbody>
				<tr>
					<td>keplr - juno</td>
					<td>{{ junoInKeplrWallet.address }}</td>
					<td>
						<button className="bg-green-300 px-1" @click="junoInKeplrWallet.connect.value()">
							connect
						</button>
					</td>
					<td>
						<button className="bg-red-300 px-1" @click="junoInKeplrWallet.disconnect.value()">
							disconnect
						</button>
					</td>
				</tr>
				<tr>
					<td>keplr - stargaze</td>
					<td>{{ stargazeInKeplrWallet.address }}</td>
					<td>
						<button className="bg-green-300 px-1" @click="stargazeInKeplrWallet.connect.value()">
							connect
						</button>
					</td>
					<td>
						<button className="bg-red-300 px-1" @click="stargazeInKeplrWallet.disconnect.value()">
							disconnect
						</button>
					</td>
				</tr>
				<tr>
					<td>leap - juno</td>
					<td>{{ junoInLeapWallet.address }}</td>
					<td>
						<button className="bg-green-300 px-1" @click="junoInLeapWallet.connect.value()">
							connect
						</button>
					</td>
					<td>
						<button className="bg-red-300 px-1" @click="junoInLeapWallet.disconnect.value()">
							disconnect
						</button>
					</td>
				</tr>
				<tr>
					<td>leap - stargaze</td>
					<td>{{ stargazeInLeapWallet.address }}</td>
					<td>
						<button className="bg-green-300 px-1" @click="stargazeInLeapWallet.connect.value()">
							connect
						</button>
					</td>
					<td>
						<button className="bg-red-300 px-1" @click="stargazeInLeapWallet.disconnect.value()">
							disconnect
						</button>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</template>

<style scoped></style>
