// examples/react/src/pages/use-chain.tsx
import { useState } from "react";
import { useChain, useWalletManager } from "@interchain-kit/react";
import { Chain } from "@chain-registry/types";

const UseChain = () => {
  const [chainName, setChainName] = useState("osmosis");
  const walletManager = useWalletManager();
  const {
    logoUrl,
    address,
    status,
    username,
    wallet,
    openView,
    rpcEndpoint,
    disconnect,
    connect,
  } = useChain(chainName);

  console.log(wallet);

  return (
    <div className="space-y-4 mx-auto max-w-3xl mt-20">
      <h1 className="text-2xl font-semibold">useChain usage:</h1>
      <select
        value={chainName}
        onChange={(e) => setChainName(e.target.value)}
        className="h-9 px-3 mr-4 border rounded-md shadow-sm"
      >
        {walletManager.chains.map((chain: Chain) => (
          <option key={chain.chainId} value={chain.chainName}>
            {chain.chainName}
          </option>
        ))}
        {/* <option value="juno">Juno</option>
        <option value="osmosis">Osmosis</option>
        <option value="stargaze">Stargaze</option>
        <option value="cosmoshub">Cosmos Hub</option> */}
      </select>
      <div className="flex items-center">
        <span className="font-bold">logo:</span>{" "}
        <img className="w-[40px] h-[40px]" src={logoUrl} alt="logoUrl" />
      </div>
      <div>
        <span className="font-bold">rpcEndpoint: {rpcEndpoint as string}</span>
      </div>
      <div>
        <span className="font-bold">current wallet: </span>
        {wallet?.info?.prettyName}
      </div>
      <div>
        <span className="font-bold">wallet status: </span>
        {status === "Connected" ? (
          <span className="text-green-900">Connected</span>
        ) : (
          status
        )}

        <button
          className="text-red-600 underline cursor-pointer ml-5"
          onClick={disconnect}
        >
          disconnect
        </button>

        <span className="text-red-600">Disconnected</span>
        <button
          className="text-blue-600 underline cursor-pointer ml-5"
          onClick={connect}
        >
          connect
        </button>
      </div>
      <div>
        <span className="font-bold">username: </span>
        {username}
      </div>
      <div className="flex items-center">
        <span className="font-bold">account address: </span>
        {address}
      </div>
    </div>
  );
};
export default UseChain;

// examples/vue/src/views/use-chain.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useChain } from '@interchain-kit/vue';
import { coins } from "@cosmjs/amino";

const chainName = ref('osmosistestnet')
const { 
  logoUrl, openView, connect, disconnect, wallet, address, 
  status, username, message, chain, getSigningCosmosClient, rpcEndpoint,
  queryClient,
} = useChain(chainName);

const recipientAddress = ref('')
const amount = ref('')
const isSending = ref(false)
const balance = ref('0')

const getBalance = async() => {
  if (queryClient.value && address.value) {
    const {balance: bc} =  await queryClient.value.balance({
      address: address.value,
      denom: chain.value.staking?.stakingTokens[0].denom as string,
    })
    if (bc?.amount) {
      balance.value = bc.amount
    } else {
      balance.value = '0'
    }
  }
}

const handleSendToken = async() => {
  const denom = chain.value.staking?.stakingTokens[0].denom as string;

  const fee = {
    amount: coins(25000, denom),
    gas: "1000000",
  };

  try {
    isSending.value = true
    let signingCosmosClient = await getSigningCosmosClient.value()
    const tx = await signingCosmosClient.helpers.send(
      address.value,
      {
        fromAddress: address.value,
        toAddress: recipientAddress.value,
        amount: [
          { denom, amount: amount.value },
        ],
      },
      fee,
      "test"
    );
    console.log('tx', tx);
    alert('Transaction was successful!')
    amount.value = ''
  } catch (error) {
    console.error(error);
  } finally {
    isSending.value = false
  }
}
</script>

<template>
  <div>
    <select
      v-model="chainName"
      className="h-9 px-3 mr-4 border rounded-md shadow-sm"
    >
      <option value="osmosistestnet">Osmosis Testnet</option>
      <option value="juno">Juno</option>
      <option value="osmosis">Osmosis</option>
      <option value="stargaze">Stargaze</option>
      <option value="cosmoshub">Cosmos Hub</option>
    </select>
    logo: <img :src="logoUrl" alt="" style="width: 30px;" />
    <div>rpcEndpoint: {{ rpcEndpoint }}</div>
    <div>address: {{ address }}</div>
    <div>balance: {{ balance }} <button @click="getBalance">getBalance</button></div>
    <div>walletStatus: {{ status  }}</div>
    <div>username: {{ username }}</div>
    <div>message: {{ message }}</div>
    <button @click="openView">openView</button>
    <button v-if="status !== 'Connected'" @click="connect">connect</button>
    <button v-if="status === 'Connected'" @click="disconnect">disconnect</button>
    <div>
      <div>amount: <input v-model="amount" type="text" /></div>
      <div>recipient address: <input v-model="recipientAddress" type="text" style="width: 400px;" /></div>
      <button @click="handleSendToken" :disabled="!recipientAddress && !amount">send</button>
    </div>
  </div>
</template>

<style scoped>

</style>
