// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { useChain } from '@interchain-kit/vue';
import { coins } from "@cosmjs/amino";
const chainName = ref('osmosistestnet')
const { 
  logoUrl, openView, disconnect, wallet, address, 
  status, username, message, chain, getSigningCosmosClient, rpcEndpoint,
  queryClient
} = useChain(chainName.value);
const recipientAddress = ref('')
const amount = ref('')
const isSending = ref(false)
const balance = ref('0')
console.log('wallet', wallet)

watch(queryClient, async(client) => {
  if (client) {
    const {balance: bc} =  await queryClient.value.balance({
      address: address.value,
      denom: chain.staking?.stakingTokens[0].denom as string,
    })
    if (bc?.amount) {
      balance.value = bc.amount
    }
  }
})

const handleSendToken = async() => {
  console.log(amount.value, recipientAddress.value)
  const denom = chain.staking?.stakingTokens[0].denom as string;

  const fee = {
    amount: coins(25000, denom),
    gas: "1000000",
  };

  try {
    isSending.value = true
    let signingCosmosClient = await getSigningCosmosClient()
    const tx = await signingCosmosClient.helpers.send(
      address.value,
      {
        fromAddress: address.value,
        toAddress: recipientAddress.value,
        amount: [
          { denom, amount: amount.value },
        ],
      },
      fee,
      "test"
    );
    console.log('tx', tx);
    alert('Transaction was successful!')
    amount.value = ''
  } catch (error) {
    console.error(error);
  } finally {
    isSending.value = false
  }
}
</script>

<template>
  <div>
    <select
      :v-model="chainName"
      className="h-9 px-3 mr-4 border rounded-md shadow-sm"
    >
      <option value="osmosistestnet">Osmosis Testnet</option>
      <option value="juno">Juno</option>
      <option value="osmosis">Osmosis</option>
      <option value="stargaze">Stargaze</option>
      <option value="cosmoshub">Cosmos Hub</option>
    </select>
    logo: <img :src="logoUrl" alt="" style="width: 30px;" />
    <div>rpcEndpoint: {{ rpcEndpoint }}</div>
    <div>address: {{ address }}</div>
    <div>balance: {{ balance }}</div>
    <div>walletStatus: {{ status  }}</div>
    <div>username: {{ username }}</div>
    <div>message: {{ message }}</div>
    <button @click="openView">connect</button>
    <button @click="disconnect">disconnect</button>
    <div>
      <div>amount: <input v-model="amount" type="text" /></div>
      <div>recipient address: <input v-model="recipientAddress" type="text" style="width: 400px;" /></div>
      <button @click="handleSendToken" :disabled="!recipientAddress && !amount">send</button>
    </div>
  </div>
</template>

<style scoped>

</style>

// examples/react/src/App.tsx
import { assetLists, chains } from '@chain-registry/v2'
import { BaseWallet, WCWallet } from '@interchain-kit/core'
import { useChainWallet, useConfig, useWalletManager } from '@interchain-kit/react'
import { useEffect, useRef, useState } from 'react'
import { creditFromStarship, makeKeplrChainInfo } from './utils'
import { Chain, Asset } from '@chain-registry/v2-types'
import { coins } from '@cosmjs/amino';
import { ChainInfo } from '@keplr-wallet/types'
import QRCode from "react-qr-code";

type BalanceProps = {
  address: string
  wallet: BaseWallet
  chainName: string
  chainId: string
  chain: Chain
}

const BalanceTd = ({ address, wallet, chain }: BalanceProps) => {

  const [balance, setBalance] = useState<string | undefined>('')
  const { queryClient } = useChainWallet(chain.chainName, wallet.option?.name as string)

  useEffect(() => {
    if (address && wallet && chain) {
      getBalance()
    }
  }, [address, wallet, chain])

  const getBalance = async () => {
    try {
      const { balance } = await queryClient.balance({ address, denom: chain.staking?.stakingTokens[0].denom as string })
      setBalance(balance?.amount)
    } catch (error) {
      console.error(error)
    }
  }

  const handleFaucet = async () => {
    await creditFromStarship('http://localhost:8003/credit', address, chain.staking?.stakingTokens[0].denom as string)
    await getBalance()
  }

  return (
    <td>
      <div><button onClick={handleFaucet}>faucet from starship</button></div>
      <div><button onClick={getBalance}>refresh balance</button></div>
      <div><span>balance: </span><span>{balance}</span></div>
    </td>
  )
}

type SendTokenProps = {
  wallet: BaseWallet,
  address: string,
  chain: Chain
}
const SendTokenTd = ({ wallet, address, chain }: SendTokenProps) => {
  const { signingStargateClient } = useChainWallet(chain.chainName, wallet.option?.name as string)

  const ref = useRef<HTMLInputElement>(null)
  const amountRef = useRef<HTMLInputElement>(null)

  const handleSendToken = async () => {
    if (ref.current) {
      const recipientAddress = ref.current.value
      const denom = chain.staking?.stakingTokens[0].denom as string

      const fee = {
        amount: coins(25000, denom),
        gas: "1000000",
      };

      try {
        const tx = await signingStargateClient.helpers.send(address, { fromAddress: address, toAddress: recipientAddress, amount: [{ denom: denom, amount: amountRef.current?.value as string }] }, fee, 'test')
        console.log(tx)
      } catch (error) {
        console.error(error)
      }
    }
  }

  return (
    <td>
      <div>
        <button onClick={handleSendToken}>Send Token to:</button>
        <input ref={ref} />
      </div>
      <div>amount: <input ref={amountRef} /></div>
    </td>
  )
}

const ChainRow = ({ chain, wallet }: { chain: Chain, wallet: BaseWallet }) => {
  const { address } = useChainWallet(chain.chainName, wallet.option?.name as string)
  return (
    <tr>
      <td>{chain.chainName}</td>
      <td>{chain.chainId}</td>
      <td>{address}</td>
      <BalanceTd address={address} chainId={chain.chainId} chainName={chain.chainName} wallet={wallet} chain={chain} />
      <SendTokenTd address={address} wallet={wallet} chain={chain} />
    </tr>
  )
}

const WalletConnectTd = ({ wallet }: { wallet: BaseWallet }) => {

  const walletManager = useWalletManager()

  const chainIds = walletManager.chains.map(c => c.chainId)

  const currentWallet = walletManager.wallets.find((w: BaseWallet) => w.option?.name === wallet.option?.name)

  const [url, setUrl] = useState<string>('')

  const [approved, setApproved] = useState<boolean>(false)

  const connect = () => {
    walletManager.connect(wallet.option?.name as string, () => setApproved(true), (uri: string) => {
      console.log({ uri })
      setUrl(uri)
    })
  }

  const disconnect = () => {
    const x = (currentWallet as WCWallet).signClient.session
    console.log(x);
    // console.log((currentWallet as WCWallet).signClient.core.pairing.getPairings())
    (currentWallet as WCWallet).signClient.core.pairing.getPairings().forEach((pairing) => {
      console.log(pairing);
      (currentWallet as WCWallet).signClient.disconnect({ topic: pairing.topic, reason: { code: 6000, message: 'disconnect' } })
    })
    if (currentWallet) {
      currentWallet.disconnect(chainIds)
    }
  }


  return (
    <td>
      <button onClick={connect}>connect</button>
      <button onClick={disconnect}>disconnect</button>
      {currentWallet instanceof WCWallet && url !== '' && !approved && <QRCode value={url} />}
      {wallet.errorMessage}
    </td>
  )
}

const E2ETest = () => {
  const walletManager = useWalletManager()

  const addChain = async () => {

    const keplrExtension = walletManager.wallets.find(w => w.option?.name === 'keplr-extension')

    const chain = chains.find(c => c.chainName === 'cosmoshub')
    const assetList = assetLists.find(a => a.chainName === 'cosmoshub')

    const chainInfo: ChainInfo = makeKeplrChainInfo(
      chain as Chain,
      assetList?.assets[0] as Asset,
      'http://localhost:26653',
      'http://localhost:1313',
      'test-cosmoshub-4',
      'cosmoshub')

    keplrExtension?.addSuggestChain(chainInfo)
  }

  return (
    <div>
      <table style={{ width: '1000px' }}>
        <thead>
          <tr>
            <th>Name</th>
            <th>Pretty Name</th>
            <th>Connect</th>
            <th>Chain</th>
          </tr>
        </thead>
        <tbody>
          {walletManager.wallets.map(wallet => {
            return (<tr>
              <td>{wallet.option?.name}</td>
              <td>{wallet.option?.prettyName}</td>
              <WalletConnectTd wallet={wallet} />
              <td>
                <table>
                  <thead>
                    <tr>
                      <th>name</th>
                      <th>chainId</th>
                      <th>address</th>
                      <th>faucet</th>
                      <th>send token</th>
                    </tr>
                  </thead>
                  <tbody>
                    {walletManager.chains.map(chain => {
                      return <ChainRow chain={chain} wallet={wallet} />
                    })}
                  </tbody>
                </table>
              </td>
            </tr>)
          })}
        </tbody>

      </table >
      <button onClick={addChain}>add suggest chain</button>
    </div>

  )

}


export default E2ETest
